force-app/main/default/objects/Chat_Event__c/Chat_Event__c.object-meta.xml
<CustomObject>
    <label>Chat Event</label>
    <nameField>
        <displayFormat>CE-{0000000}</displayFormat>
        <label>Chat Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat_Event__c/fields/Chat_Transcript__c.field-meta.xml
<CustomField>
    <fullName>Chat_Transcript__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chat Transcript</label>
    <referenceTo>LiveChatTranscript</referenceTo>
    <relationshipLabel>Chat Events</relationshipLabel>
    <relationshipName>Chat_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chat_Event__c/fields/Intent__c.field-meta.xml
<CustomField>
    <fullName>Intent__c</fullName>
    <label>Intent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chat_Event__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chat_Event__c/fields/Sentiment__c.field-meta.xml
<CustomField>
    <fullName>Sentiment__c</fullName>
    <label>Sentiment</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chat_Event__c/fields/Spoken_By__c.field-meta.xml
<CustomField>
    <fullName>Spoken_By__c</fullName>
    <label>Spoken By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chat_Event__c/fields/Transcript__c.field-meta.xml
<CustomField>
    <fullName>Transcript__c</fullName>
    <label>Transcript</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Chat_Event__c/fields/Translation__c.field-meta.xml
<CustomField>
    <fullName>Translation__c</fullName>
    <label>Translation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chat_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Speech</fullName>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Calendar</fullName>
            </value>
            <value>
                <fullName>Map</fullName>
            </value>
            <value>
                <fullName>Breakpoint</fullName>
            </value>
            <value>
                <fullName>Money</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Einstein Insight</fullName>
            </value>
            <value>
                <fullName>End Chat</fullName>
            </value>
            <value>
                <fullName>Translation</fullName>
            </value>
            <value>
                <fullName>Intent</fullName>
            </value>
            <value>
                <fullName>Sentiment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chat_Event_Entity__c/Chat_Event_Entity__c.object-meta.xml
<CustomObject>
    <label>Chat Event Entity</label>
    <nameField>
        <label>Chat Event Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chat Event Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat_Event_Entity__c/fields/Chat_Event__c.field-meta.xml
<CustomField>
    <fullName>Chat_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chat Event</label>
    <referenceTo>Chat_Event__c</referenceTo>
    <relationshipLabel>Chat Event Entities</relationshipLabel>
    <relationshipName>Chat_Event_Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chat_Event_Entity__c/fields/Confidence__c.field-meta.xml
<CustomField>
    <fullName>Confidence__c</fullName>
    <label>Confidence</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Chat_Event_Entity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chat_Event_Entity__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChatInterceptCtrl.cls
public class ChatInterceptCtrl {
    
    @AuraEnabled
    public static Chat_Event__c analyseChatString(String chatString, String toLanguage, String chatId, String spokenBy, String intentModel, Integer currentSentiment, Integer currentPosition){
        //Comment from Neil
        //Second Comment from Neil
        String translation = chatString;
        if (toLanguage != null){
            translation = getChatTranslation(chatString, toLanguage, spokenBy);            
        }
        String intent;
        String sentiment;
        if (spokenBy == 'Customer'){
            intent = getChatIntent(translation, intentModel, spokenBy);
            sentiment = getChatSentiment(translation, spokenBy);
        } else {
            sentiment = getChatSentiment(chatString, spokenBy);
        }
        einsteinplay.Einstein_PredictionResult prediction;
        if (spokenBy == 'Customer'){
            prediction = getChatNER(chatString, spokenBy);
        }
        currentSentiment = (currentSentiment == null ? 0 : currentSentiment);
        Chat_Event__c chatEvent = insertChatEvent(chatId, chatString, spokenBy, translation, intent, sentiment, currentSentiment, currentPosition);
        
        List<Chat_Event_Entity__c> entities = insertChatEventEntities(chatEvent.Id, prediction);
        
        chatEvent = [
            SELECT 	Name, Event_Time__c , Type__c, Transcript__c, Spoken_By__c, 
            		Translation__c, Intent__c, Aggregated_Sentiment__c, Sentiment__c,
            		(SELECT Type__c, Value__c, Confidence__c FROM Chat_Event_Entities__r) 
            FROM 	Chat_Event__c 
            WHERE 	ID =:chatEvent.Id
        ];
        
        //Placeholder for doing NER on chatString
        
        return chatEvent;
    }
    
    @AuraEnabled
    public static List<Chat_Event__c> getPastChatEvents(String chatId){
        System.debug('Chat Id is ' + chatId);
        return [
            SELECT  Name, Event_Time__c , Type__c, Transcript__c, Spoken_By__c, 
                    Translation__c, Intent__c, Aggregated_Sentiment__c, Sentiment__c,
                    (SELECT Type__c, Value__c, Confidence__c FROM Chat_Event_Entities__r) 
            FROM    Chat_Event__c 
            WHERE   Chat_Transcript__c  =: chatId 
            ORDER BY Event_Time__c ASC];
    }

    @AuraEnabled
    public static String getChatTranslation(String chatString, String toLanguage, String spokenBy){
        System.debug('About to translate ' + chatString + ' to language ' + toLanguage);
        String resultString = AITools.MLServices.translate(chatString, toLanguage, 'auto');
        System.debug('Translated ' + resultString);
        return resultString;
    }
    
    @AuraEnabled
    public static String getChatIntent(String chatString, String intentModel, String spokenBy){
        String resultString;
        if (intentModel != ''){
            List<Language.Prediction> intentList = Language.intent(chatString, language.getAccessToken(), intentModel);
            if (intentList.size()>0 && intentList[0].probability > 0.9){
                resultString = intentList[0].label;
            }
        }
        return resultString;
    }
    
    @AuraEnabled
    public static String getChatEntities(String chatString){
        String resultString = '';
        return resultString;
    }
    
    @AuraEnabled
    public static String getChatSentiment(String chatString, String spokenBy){
        String resultString = '';
        List<Language.Prediction> sentimentList = Language.sentiment(chatString, language.getAccessToken(), 'CommunitySentiment');
        if (sentimentList.size()>0){
            resultString = sentimentList[0].label;
        }
        return resultString;
    }
    
    // NER 
    @AuraEnabled
    public static einsteinplay.Einstein_PredictionResult getChatNER(String chatString, String spokenBy){
        String resultString = '';
        String modelId = 'NER7'; 
        einsteinplay.Einstein_PredictionService service = new einsteinplay.Einstein_PredictionService(einsteinplay.Einstein_PredictionService.Types.NER); 
        einsteinplay.Einstein_PredictionResult prediction = service.predictNER(modelId,chatString,3,'');
        return prediction; 
    }
    
    
    @AuraEnabled
    public static Chat_Event__c insertChatEvent(String chatId, String chatTranscript, String spokenBy, String chatTranslation, String chatIntent, String chatSentiment, Integer currentSentiment, Integer currentPosition){
        Chat_Event__c chatEvent = new Chat_Event__c();
        chatEvent.Type__c = 'Speech';
        chatEvent.Chat_Transcript__c = chatId;
        chatEvent.Transcript__c = chatTranscript;
        chatEvent.Spoken_By__c = spokenBy;
        chatEvent.Event_Time__c = DateTime.now();
        chatEvent.Translation__c = chatTranslation;
        chatEvent.Intent__c = chatIntent;
        chatEvent.Position__c = currentPosition;
        
        //Calculate Sentiment
        chatEvent.Sentiment__c = chatSentiment;
        
        if (spokenBy == 'Customer'){
            if (chatSentiment == 'Positive'){
                chatEvent.Aggregated_Sentiment__c = currentSentiment + 1;
            } else if (chatSentiment == 'Negative'){
                chatEvent.Aggregated_Sentiment__c = currentSentiment -1;
            } else {
                chatEvent.Aggregated_Sentiment__c = currentSentiment;
            } 
        } else {
            chatEvent.Aggregated_Sentiment__c = currentSentiment;
        }
        
        insert chatEvent;
        return chatEvent;
    }
    @AuraEnabled
    public static List<Chat_Event_Entity__c> insertChatEventEntities(String eventId, einsteinplay.Einstein_PredictionResult prediction){
        List<Chat_Event_Entity__c> entityList = new List<Chat_Event_Entity__c>();
        for(einsteinplay.Einstein_Probability probability : prediction.probabilities){
            Chat_Event_Entity__c eventEntity = new Chat_Event_Entity__c();
            eventEntity.Type__c = probability.label;
            eventEntity.Value__c = probability.token;
            eventEntity.Confidence__c = probability.probability;
            eventEntity.Chat_Event__c = eventId;
            entityList.add(eventEntity);
        }
        insert entityList;
        return entityList;
    }
    
    
    @AuraEnabled
    public static list<Chat_Event__c> fetchChatEventList(String chatId){
        return [SELECT Name, Event_Time__c , Type__c, Transcript__c, Spoken_By__c, URL__c FROM Chat_Event__c WHERE Chat_Transcript__c =: chatId ORDER BY Event_Time__c ASC];
    }
}